apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-workflow-config
  namespace: ai-workflow
data:
  AWS_REGION: "us-east-2"
  APP_ENV: "dev"
  ENVIRONMENT: "dev"
  WORKFLOW_QUEUE_URL: "REPLACE_WITH_WORKFLOW_QUEUE_URL"
  WORKFLOW_TABLE_NAME: "workflow_definitions"
  WORKFLOW_RUN_TABLE_NAME: "workflow_runs"
  DYNAMODB_WORKFLOW_RUNS_TABLE: "workflow_runs"
  OPENAI_MODEL: "gpt-4o-mini"
  PYTHONUNBUFFERED: "1"
