apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-workflow-listener
  namespace: ai-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-workflow-listener
  template:
    metadata:
      labels:
        app: ai-workflow-listener
    spec:
      serviceAccountName: ai-workflow-sa
      containers:
        - name: ai-workflow-listener
          image: 163596510317.dkr.ecr.us-east-2.amazonaws.com/ai-workflow-service:latest
          imagePullPolicy: Always
          command:
            - python
            - -m
            - app.listeners.workflow_execution_listener
          envFrom:
            - configMapRef:
                name: ai-workflow-config
            - secretRef:
                name: ai-workflow-secret
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
